// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_app from "./routes/_app.tsx";
import * as $ExpandableInput from "./islands/ExpandableInput.tsx";
import * as $Form from "./islands/Form.tsx";
import * as $MicroHeaderSetup from "./islands/MicroHeaderSetup.tsx";
import * as $MinicartTotalInstallments from "./islands/MinicartTotalInstallments.tsx";
import * as $Product_TrustVox from "./islands/Product/TrustVox.tsx";
import * as $ProductStars from "./islands/ProductStars.tsx";
import * as $ProductSubscription from "./islands/ProductSubscription.tsx";
import * as $Seals_RaVerifiedSeal from "./islands/Seals/RaVerifiedSeal.tsx";
import * as $Shipping from "./islands/Shipping.tsx";
import * as $Sort from "./islands/Sort.tsx";
import * as $SwiperJS from "./islands/SwiperJS.tsx";
import { type Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_app.tsx": $_app,
  },
  islands: {
    "./islands/ExpandableInput.tsx": $ExpandableInput,
    "./islands/Form.tsx": $Form,
    "./islands/MicroHeaderSetup.tsx": $MicroHeaderSetup,
    "./islands/MinicartTotalInstallments.tsx": $MinicartTotalInstallments,
    "./islands/Product/TrustVox.tsx": $Product_TrustVox,
    "./islands/ProductStars.tsx": $ProductStars,
    "./islands/ProductSubscription.tsx": $ProductSubscription,
    "./islands/Seals/RaVerifiedSeal.tsx": $Seals_RaVerifiedSeal,
    "./islands/Shipping.tsx": $Shipping,
    "./islands/Sort.tsx": $Sort,
    "./islands/SwiperJS.tsx": $SwiperJS,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
